name: Test homeWork06

on:
  push:
    paths:
     - ".github/workflows/run_test_hw6_t.yaml"
     - "homeWork/06/stl/**"
     - "!homeWork/06/tests/**"
  pull_request:
    paths:
     - ".github/workflows/run_test_hw6_t.yaml"
     - "homeWork/06/stl/**"
     - "!homeWork/06/tests/**"


env:
  BUILD_TYPE: Release
  WORK_DIR: homeWork/06

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      working-directory: ${{github.workspace}}/${{env.WORK_DIR}}/
      run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/${{env.WORK_DIR}}/
      run: cmake --build ./build --target Google_Tests_run_stl --config ${{env.BUILD_TYPE}}

    - name: Tests
      working-directory: ${{github.workspace}}/${{env.WORK_DIR}}/
      run: build/Google_Tests_run_stl
      shell: bash