name: Test homeWork02

on:
  push:
    paths:
     - ".github/workflows/run_test_hw2_t.yaml"
     - "homeWork/02/cstack/**"
     - "homeWork/02/tests/**"
  pull_request:
    paths:
     - ".github/workflows/run_test_hw2_t.yaml"
     - "homeWork/02/cstack/**"
     - "homeWork/02/tests/**"


env:
  BUILD_TYPE: Release
  WORK_DIR: homeWork/02

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      working-directory: ${{github.workspace}}/${{env.WORK_DIR}}/
      run: cmake -B ./build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      working-directory: ${{github.workspace}}/${{env.WORK_DIR}}/
      run: cmake --build ./build --target Google_Tests_run_cstack --config ${{env.BUILD_TYPE}}

    - name: Tests
      working-directory: ${{github.workspace}}/${{env.WORK_DIR}}/
      run: build/Google_Tests_run_cstack
      shell: bash