name: Test task8

on:
  push:
    paths:
     - ".github/workflows/run_test_hw8_t.yaml"
     - "homeWork/08/main.cpp"
     - "homeWork/08/rectangle.h"
     - "homeWork/08/file_reader_raii.h"
  pull_request:
    paths:
     - ".github/workflows/run_test_hw8_t.yaml"
     - "homeWork/08/main.cpp"
     - "homeWork/08/rectangle.h"
     - "homeWork/08/file_reader_raii.h"


env:
  TASK_DIR: ${{github.workspace}}/homeWork/08/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      working-directory: ${{env.TASK_DIR}}
      run: make config

    - name: Build
      working-directory: ${{env.TASK_DIR}}
      run: make build

    - name: Valgrind
      run: sudo apt-get install -y valgrind
      shell: bash

    - name: Tests
      working-directory: ${{env.TASK_DIR}}
      run: make test
      shell: bash
